var pi= Math.PI
console.log("pi value is:" , pi);
console.log("return euler number", Math.E);
var a = Math.abs(7.25);
var b = Math.abs(-7.25);
var c = Math.abs(null);
var d = Math.abs("Hello");
var e = Math.abs(-2-3);
console.log("returns absolute value:", a);
console.log("returns absolute value:", b);
console.log("returns absolute value:", c);
console.log("returns absolute value:", d);
console.log("returns absolute value:", e);
var x = Math.acos(1);
var y = Math.acos(0);
var z = Math.acos(-1);
console.log("method returns a value value between 0 and PI:", x);
console.log("method returns a value value between 0 and PI:", y);
console.log("method expects a parameter in the range -1 to 1:", z);
var arcosh = Math.acosh(7);
console.log("returns the hyperbolic arc-cosine of a number:" , arcosh);
var arcosh1 = Math.acosh(-7);
console.log("If the parameter is less than 1, the method returns NaN:" , arcosh1);
var asin =Math.asin(-1);
var asin1 =Math.asin(0);
var asin2 =Math.asin(1);
console.log("method returns a value between -PI/2 and PI/2:", asin);
console.log("method expects a parameter in the range -1 to 1:", asin1);
console.log("method returns a value between -PI/2 and PI/2:", asin2);
var asinh = Math.asinh(4);
var asinh1 = Math.asinh(6);
console.log("method returns the hyperbolic arc-sine of a number:" ,asinh );
console.log("method returns the hyperbolic arc-sine of a number:" ,asinh1 );
var atan = Math.atan(2);
console.log("method returns the arctangent of a number as a value between -PI/2 and PI/2 radians:" , atan);
var atan2= Math.atan2(8,4);
console.log("had a point with the (x,y) coordinates of (4,8), you could calculate the angle in radians between that point and the positive X axis:" , atan2);;
var atanh=Math.atanh(0.5);
var atanh1=Math.atanh(1);
var atanh2=Math.atanh(-1);
console.log("method returns Infinity if the number is 1:" , atanh1 );
console.log("method returns -Infinity if the number is -1:", atanh2);
console.log("Math.atanh() returns the hyperbolic arctangent of a number:" ,atanh );
var round = Math.round(2.5);
console.log("round of the nearest integer:" , round);
var ceil = Math.ceil(4.1);
var ceil1 = Math.ceil(-4.1);
console.log("round of the nearest integer:" , ceil);
console.log("round of the nearest integer:" , ceil1);
var floor = Math.floor(4.7);
console.log("returns the value of x rounded down to its nearest integer:", floor);
var trunc = Math.trunc(-3.5);
console.log("returns the integer part of x:" , trunc);
var sign = Math.sign(4);
var sign1 = Math.sign(0);
var sign2= Math.sign(-4);
console.log("returns if x is negative, null or positive:",sign );
console.log("returns if x is negative, null or positive:",sign1 );
console.log("returns if x is negative, null or positive:",sign2 );
var pow = Math.pow(2 ,4);
console.log("return the value of x  to the power of y  :",pow );
var sqrt = Math.sqrt(64);
console.log("return the square root of value:" , sqrt);
var abs = Math.abs(-4.7);
console.log("rteurn positive value of x :", abs);
var min = Math.min(2, 3 , 4, -5);
console.log("yoused to find lowest value:" , min);
var max = Math.max(6, 7, 8, 9);
console.log("youse to find highest value:" ,max );
var max = (Math.floor(Math.random() * 200) + 1);
console.log(max);

